"""
Goal-Driven Trading OS — Curated Strategy Library
经过验证的交易策略库，数据来源：tastytrade, Option Alpha, 学术研究
"""

STRATEGY_LIBRARY = [
    {
        "id": "wheel_strategy",
        "name": "Wheel 策略",
        "description": "先卖 Put 收权利金，若被行权则持股再卖 Covered Call，循环收租。适合对标的长期看好、希望持续获得收入的投资者。整个循环相当于以折扣价买股后高价卖出。",
        "source": "tastytrade",
        "instrument": "sell_put",
        "direction": "neutral",
        "style": "income",
        "risk_level": "medium",
        "annual_return_range": [15, 30],
        "win_rate_pct": 72,
        "params": {
            "delta_target": 0.3,
            "dte_min": 30,
            "dte_max": 45,
            "profit_target": 0.5,
            "stop_loss_pct": -2.0,
        },
        "tags": ["期权", "卖方", "收入", "Wheel"],
        "why_it_works": "结合卖 Put 收权利金和股票被动买入两种优势，统计上 70-75% 的短期 Put 到期无价值，时间价值持续流向卖方。",
        "best_market": "低波动率横盘或缓慢上涨市场，VIX 15-25",
        "worst_market": "急剧下跌（gap down）行情，持仓可能大幅亏损",
    },
    {
        "id": "naked_sell_put",
        "name": "裸卖 Put（收租型）",
        "description": "直接卖出虚值 Put 期权收取权利金，不需持有股票。适合对标的看涨或中性、希望以低价买入的投资者。需要足够保证金，风险为股价大跌至0。",
        "source": "tastytrade",
        "instrument": "sell_put",
        "direction": "neutral",
        "style": "income",
        "risk_level": "high",
        "annual_return_range": [20, 40],
        "win_rate_pct": 70,
        "params": {
            "delta_target": 0.25,
            "dte_min": 21,
            "dte_max": 45,
            "profit_target": 0.5,
            "stop_loss_pct": -2.0,
            "min_iv_rank": 30,
        },
        "tags": ["期权", "卖方", "收入", "高收益"],
        "why_it_works": "期权时间价值每天流逝（Theta），卖方天然处于统计优势一侧。SPY Put 历史胜率约68-72%。",
        "best_market": "IV Rank > 30，市场横盘或缓涨，VIX 15-30",
        "worst_market": "系统性崩跌（2020年3月类），损失可达10-20倍权利金",
    },
    {
        "id": "cash_secured_put",
        "name": "现金担保 Put（保守型）",
        "description": "卖出 Put 的同时持有足额现金作为担保，等于以折扣价预购股票。若不被行权则保留权利金，若被行权则以目标价格买入股票。",
        "source": "Option Alpha",
        "instrument": "sell_put",
        "direction": "neutral",
        "style": "income",
        "risk_level": "low",
        "annual_return_range": [8, 18],
        "win_rate_pct": 72,
        "params": {
            "delta_target": 0.2,
            "dte_min": 30,
            "dte_max": 45,
            "profit_target": 0.5,
            "stop_loss_pct": -2.0,
        },
        "tags": ["期权", "卖方", "保守", "收入"],
        "why_it_works": "以低于市价的目标价预购股票，同时收取权利金降低成本基础，长期胜率70%以上。",
        "best_market": "你愿意持有该股票，IV适中偏高，VIX 15-25",
        "worst_market": "股价大幅下跌后，持股成本高于市价",
    },
    {
        "id": "covered_call",
        "name": "Covered Call（持股收租）",
        "description": "持有100股股票同时卖出 Call 期权收取权利金，降低持仓成本。若 Call 被行权则以目标价格卖出股票获利，若未被行权则保留权利金。",
        "source": "tastytrade",
        "instrument": "covered_call",
        "direction": "neutral",
        "style": "income",
        "risk_level": "low",
        "annual_return_range": [10, 20],
        "win_rate_pct": 65,
        "params": {
            "delta_target": 0.3,
            "dte_min": 21,
            "dte_max": 45,
            "profit_target": 0.5,
            "otm_pct": 0.03,
        },
        "tags": ["期权", "卖方", "收入", "持股"],
        "why_it_works": "在持股基础上额外收取期权权利金，平均每月可增加1-3%的额外收益，CBOE BXM指数长期验证。",
        "best_market": "横盘震荡，持股微涨，VIX 12-20",
        "worst_market": "股价快速大涨时，盈利被上涨收益上限封住",
    },
    {
        "id": "iron_condor",
        "name": "铁神鹰（Iron Condor）",
        "description": "同时卖出虚值 Put 价差和虚值 Call 价差，构建有限风险的中性策略。只要标的在到期时维持在两个行权价之间就能盈利。",
        "source": "tastytrade",
        "instrument": "sell_put",
        "direction": "neutral",
        "style": "income",
        "risk_level": "medium",
        "annual_return_range": [15, 25],
        "win_rate_pct": 68,
        "params": {
            "delta_target": 0.16,
            "dte_min": 30,
            "dte_max": 45,
            "profit_target": 0.5,
            "stop_loss_pct": -2.0,
            "min_iv_rank": 30,
        },
        "tags": ["期权", "组合", "中性", "有限风险"],
        "why_it_works": "双边收取权利金，最大损失有限，适合高 IV 环境，tastyworks 研究显示 16delta 铁神鹰历史胜率约68%。",
        "best_market": "高 IV Rank（>30），预期市场小幅震荡，财报前",
        "worst_market": "VIX 急剧飙升，标的发生大幅单边行情",
    },
    {
        "id": "bull_put_spread",
        "name": "牛市价差（Bull Put Spread）",
        "description": "卖出较高行权价 Put，同时买入较低行权价 Put 作为保护。在市场温和看涨时获利，最大损失有限。比裸卖 Put 资金占用少，风险更可控。",
        "source": "Option Alpha",
        "instrument": "sell_put",
        "direction": "bullish",
        "style": "income",
        "risk_level": "medium",
        "annual_return_range": [20, 35],
        "win_rate_pct": 65,
        "params": {
            "delta_target": 0.3,
            "dte_min": 21,
            "dte_max": 45,
            "profit_target": 0.5,
            "stop_loss_pct": -1.5,
        },
        "tags": ["期权", "价差", "看涨", "有限风险"],
        "why_it_works": "在已知最大损失的前提下获取时间价值，每单位资金风险回报率高。",
        "best_market": "温和看涨市场，标的站稳支撑位，IV适中",
        "worst_market": "股价跌穿买入 Put 行权价，遭受最大损失",
    },
    {
        "id": "bear_call_spread",
        "name": "熊市价差（Bear Call Spread）",
        "description": "卖出较低行权价 Call，同时买入较高行权价 Call 作为保护。在市场温和看跌时获利，最大损失有限。",
        "source": "Option Alpha",
        "instrument": "call",
        "direction": "bearish",
        "style": "income",
        "risk_level": "medium",
        "annual_return_range": [15, 30],
        "win_rate_pct": 60,
        "params": {
            "delta_target": 0.3,
            "dte_min": 21,
            "dte_max": 45,
            "profit_target": 0.5,
            "stop_loss_pct": -1.5,
        },
        "tags": ["期权", "价差", "看跌", "有限风险"],
        "why_it_works": "在看跌预期下以定义风险获取时间价值，市场方向判断正确时回报率高。",
        "best_market": "市场高位，超买信号，趋势转弱",
        "worst_market": "市场继续强势上涨，遭受最大损失",
    },
    {
        "id": "long_leaps_call",
        "name": "Long LEAPS Call（长期看涨期权）",
        "description": "买入1年以上到期的深度实值或平值 Call 期权，用较少资金代替持股。Delta 高达0.7以上，获得近似持股的涨幅但资金占用仅为1/3至1/5。",
        "source": "CBOE Research",
        "instrument": "call",
        "direction": "bullish",
        "style": "growth",
        "risk_level": "medium",
        "annual_return_range": [20, 60],
        "win_rate_pct": 55,
        "params": {
            "delta_target": 0.7,
            "dte_min": 365,
            "dte_max": 730,
            "profit_0_4m": 0.20,
            "profit_4_6m": 0.30,
            "profit_7_9m": 0.50,
            "force_close_months": 6,
        },
        "tags": ["期权", "买方", "成长", "杠杆"],
        "why_it_works": "LEAPS Call 提供杠杆效应但最大损失有限（仅限权利金），适合对大盘科技长期看好的投资者。",
        "best_market": "牛市初期或中期，低利率环境，科技股强势",
        "worst_market": "熊市、高利率（利率上升使期权时间价值贬值更快）",
    },
    {
        "id": "poor_mans_covered_call",
        "name": "穷人版 Covered Call（PMCC）",
        "description": "用 LEAPS Call 代替持股来卖 Covered Call，资金占用仅为正常 Covered Call 的20-30%。实质是对角价差，结合 LEAPS 的杠杆与卖 Call 的时间价值收益。",
        "source": "tastytrade",
        "instrument": "covered_call",
        "direction": "neutral",
        "style": "income",
        "risk_level": "medium",
        "annual_return_range": [25, 50],
        "win_rate_pct": 60,
        "params": {
            "delta_target": 0.7,
            "dte_min": 30,
            "dte_max": 45,
            "otm_pct": 0.03,
        },
        "tags": ["期权", "组合", "收入", "LEAPS"],
        "why_it_works": "通过 LEAPS 获得低成本股票敞口，同时每月卖出 Covered Call 回收时间价值，资金效率高。",
        "best_market": "中性偏涨，VIX 15-25",
        "worst_market": "股价大幅下跌超过 LEAPS 成本，或股价大幅上涨超过近期 Call 行权价",
    },
    {
        "id": "straddle_strangle",
        "name": "买入跨式/宽跨式（Long Straddle/Strangle）",
        "description": "同时买入相同标的的 Call 和 Put，押注股价将大幅波动（方向不限）。跨式使用平值期权，宽跨式使用虚值期权（成本更低）。适合财报、重要事件前。",
        "source": "Option Alpha",
        "instrument": "call",
        "direction": "neutral",
        "style": "momentum",
        "risk_level": "high",
        "annual_return_range": [20, 80],
        "win_rate_pct": 40,
        "params": {
            "dte_min": 7,
            "dte_max": 21,
            "profit_target": 0.50,
            "stop_loss_pct": -0.5,
        },
        "tags": ["期权", "买方", "波动率", "事件驱动"],
        "why_it_works": "当实际波动率大于隐含波动率时盈利，适合低 IV 环境入场，在事件驱动行情中获取超额收益。",
        "best_market": "财报发布前、重大经济数据前，IV 处于历史低位",
        "worst_market": "IV 高位入场，事件后价格原地踏步，遭受双重时间价值损耗",
    },
    {
        "id": "momentum_buy_stock",
        "name": "动量追涨（Momentum Stock Buy）",
        "description": "买入强势突破的股票，利用价格动量效应。通常在股价突破52周高点或重要阻力位时入场，设置止损于突破点下方。基于动量因子的长期学术验证。",
        "source": "AQR Research / Jegadeesh & Titman 1993",
        "instrument": "stock",
        "direction": "bullish",
        "style": "momentum",
        "risk_level": "medium",
        "annual_return_range": [15, 30],
        "win_rate_pct": 45,
        "params": {
            "lookback_days": 252,
            "sma_200_above_pct": 0.0,
            "stop_loss_pct": -0.07,
            "position_pct": 0.05,
            "max_positions": 10,
        },
        "tags": ["正股", "动量", "趋势"],
        "why_it_works": "动量因子是最持久的股票市场异象之一，多个学术研究证实6-12个月动量策略长期跑赢基准。",
        "best_market": "牛市趋势明确，宏观环境良好，市场风险偏好高",
        "worst_market": "动量反转（崩盘后强势股最先下跌）",
    },
    {
        "id": "dip_buy_stock",
        "name": "逢低买入（Dip Buy Stock）",
        "description": "在强势股回调至支撑位时买入，通常回调5-10%且站在SMA200之上是买点。利用均值回归结合趋势跟踪，在趋势延续前的短暂回调中入场。",
        "source": "Stan Weinstein / Mark Minervini",
        "instrument": "stock",
        "direction": "bullish",
        "style": "mean_reversion",
        "risk_level": "medium",
        "annual_return_range": [12, 25],
        "win_rate_pct": 55,
        "params": {
            "dip_threshold": -0.05,
            "sma_200_above_pct": 0.0,
            "stop_loss_pct": -0.08,
            "position_pct": 0.05,
            "max_positions": 8,
        },
        "tags": ["正股", "均值回归", "支撑位"],
        "why_it_works": "在长期趋势向上的前提下，短期回调是概率更高的入场机会，均值回归效应有学术支撑。",
        "best_market": "牛市中的正常回调，标的基本面强，SMA200向上倾斜",
        "worst_market": "趋势断裂的假回调（跌破SMA200），基本面恶化",
    },
    {
        "id": "ma_crossover",
        "name": "均线交叉（MA Crossover）",
        "description": "短期均线（如10/20日）上穿长期均线（如50/200日）时买入，下穿时卖出。经典趋势跟踪策略，历史悠久，简单有效。",
        "source": "Dow Theory / Classical Technical Analysis",
        "instrument": "stock",
        "direction": "bullish",
        "style": "momentum",
        "risk_level": "low",
        "annual_return_range": [8, 15],
        "win_rate_pct": 40,
        "params": {
            "sma_short": 20,
            "sma_long": 50,
            "position_pct": 0.10,
            "stop_loss_pct": -0.05,
            "max_positions": 5,
        },
        "tags": ["正股", "趋势跟踪", "均线"],
        "why_it_works": "均线交叉过滤掉大量噪音，胜在参与大趋势行情，亏损时趋势尚未形成所以亏损小，盈利时趋势延续所以盈利大。",
        "best_market": "趋势明显的市场，单边行情",
        "worst_market": "横盘震荡市，频繁交叉导致反复止损",
    },
    {
        "id": "rsi_mean_reversion",
        "name": "RSI 均值回归",
        "description": "在 RSI 跌至超卖区域（<30）时买入，RSI 恢复至中性区（50+）时卖出。适用于有支撑的品种，在过度恐慌时逆向入场。",
        "source": "Connors Research / Larry Connors",
        "instrument": "stock",
        "direction": "bullish",
        "style": "mean_reversion",
        "risk_level": "medium",
        "annual_return_range": [15, 25],
        "win_rate_pct": 62,
        "params": {
            "rsi_threshold": 30,
            "exit_at": "mid",
            "stop_loss_pct": -0.08,
            "position_pct": 0.05,
            "sma_200_above_pct": 0.0,
        },
        "tags": ["正股", "均值回归", "超卖"],
        "why_it_works": "Connors 研究表明 RSI(2)<10 时的 SP500 成分股次日回报率显著高于随机，短期过度超卖存在统计优势。",
        "best_market": "牛市中的短暂恐慌，VIX 短期飙升后，标的基本面无实质变化",
        "worst_market": "熊市中 RSI 持续在低位，越买越跌",
    },
    {
        "id": "bollinger_band_reversion",
        "name": "布林带均值回归（BB Reversion）",
        "description": "股价触及布林带下轨时买入，反弹至中轨（SMA20）时卖出。利用价格偏离均值后回归的统计特性。",
        "source": "John Bollinger / Bollinger on Bollinger Bands",
        "instrument": "stock",
        "direction": "bullish",
        "style": "mean_reversion",
        "risk_level": "medium",
        "annual_return_range": [12, 22],
        "win_rate_pct": 60,
        "params": {
            "bb_period": 20,
            "bb_std": 2.0,
            "bb_exit": "mid",
            "stop_loss_at_mult": 3.0,
            "position_pct": 0.05,
        },
        "tags": ["正股", "均值回归", "布林带"],
        "why_it_works": "正态分布下股价触及2倍标准差的概率约5%，大多数情况会回归均值，提供良好的统计入场时机。",
        "best_market": "横盘震荡市，标的在通道内上下波动",
        "worst_market": "趋势行情中价格沿布林带下轨持续下行（带宽扩张）",
    },
    {
        "id": "tqqq_dip_buy",
        "name": "TQQQ/SQQQ 杠杆 ETF 低吸",
        "description": "在纳斯达克指数（QQQ）大幅回调时买入3倍杠杆多头 ETF（TQQQ），回弹后止盈。高风险高回报，仅适合短线操作和有明确止损纪律的交易者。",
        "source": "Option Alpha Research",
        "instrument": "stock",
        "direction": "bullish",
        "style": "momentum",
        "risk_level": "high",
        "annual_return_range": [30, 80],
        "win_rate_pct": 55,
        "params": {
            "dip_threshold": -0.05,
            "sma_200_above_pct": -0.10,
            "stop_loss_pct": -0.10,
            "profit_target": 0.15,
            "position_pct": 0.03,
            "max_positions": 3,
        },
        "tags": ["ETF", "杠杆", "动量", "高风险"],
        "why_it_works": "QQQ 长期上涨趋势叠加3倍杠杆，在大跌后反弹时放大收益。但复利衰减（volatility decay）是主要风险。",
        "best_market": "纳斯达克牛市中的短暂回调，VIX 短期飙升后",
        "worst_market": "持续熊市，杠杆衰减效应放大亏损",
    },
    {
        "id": "sma200_trend_follow",
        "name": "SMA200 趋势跟踪",
        "description": "以200日均线为牛熊分界线，价格在SMA200之上持有多头，之下持有空头或空仓。长期绩效优于买入持有，显著减少最大回撤。",
        "source": "Meb Faber / Global Asset Allocation",
        "instrument": "stock",
        "direction": "bullish",
        "style": "momentum",
        "risk_level": "low",
        "annual_return_range": [8, 15],
        "win_rate_pct": 50,
        "params": {
            "sma_200_above_pct": 0.0,
            "exit_below_sma200_pct": -0.02,
            "position_pct": 0.20,
            "max_positions": 5,
        },
        "tags": ["正股", "趋势跟踪", "SMA200"],
        "why_it_works": "Faber(2007) 研究表明 SMA10月 趋势跟踪可将年化波动率降低30-40%，同时保持相近的年化收益。",
        "best_market": "明显单边趋势市场",
        "worst_market": "频繁穿越SMA200的震荡市，产生大量假信号",
    },
    {
        "id": "qqq_leaps",
        "name": "QQQ LEAPS（长期科技看涨）",
        "description": "买入 QQQ（纳斯达克100指数ETF）的1-2年期 LEAPS Call，以20-30%的资金获得纳斯达克100的完整上涨敞口。",
        "source": "CBOE LEAPS Research",
        "instrument": "call",
        "direction": "bullish",
        "style": "growth",
        "risk_level": "medium",
        "annual_return_range": [20, 50],
        "win_rate_pct": 58,
        "params": {
            "delta_target": 0.7,
            "dte_min": 365,
            "dte_max": 730,
            "profit_0_4m": 0.25,
            "profit_4_6m": 0.40,
        },
        "tags": ["ETF", "期权", "成长", "LEAPS"],
        "why_it_works": "QQQ 过去15年平均年化涨幅约15%，LEAPS 杠杆可将这一收益放大至2-3倍，同时最大损失仅为权利金。",
        "best_market": "科技股牛市，利率宽松，AI/创新驱动",
        "worst_market": "科技股熊市（如2022年），高利率环境",
    },
    {
        "id": "vix_spike_sell_put",
        "name": "VIX 飙升卖 Put（恐慌入场）",
        "description": "在 VIX 快速飙升（>30）时卖出大盘（SPY/QQQ）的虚值 Put，利用恐慌带来的权利金大幅提升。VIX 均值回归后平仓获利。",
        "source": "tastytrade / Karen the Supertrader",
        "instrument": "sell_put",
        "direction": "neutral",
        "style": "income",
        "risk_level": "high",
        "annual_return_range": [25, 50],
        "win_rate_pct": 75,
        "params": {
            "vix_min": 28,
            "vix_max": 60,
            "delta_target": 0.2,
            "dte_min": 30,
            "dte_max": 60,
            "profit_target": 0.5,
            "stop_loss_pct": -2.0,
        },
        "tags": ["期权", "卖方", "事件驱动", "VIX"],
        "why_it_works": "VIX 均值回归特性显著，高 VIX 期间卖 Put 权利金远超正常水平，平均年化权利金可达4-8%/月。",
        "best_market": "VIX > 30 的恐慌行情，市场无实质性崩溃风险",
        "worst_market": "真实熊市（如2008年、2020年3月），VIX 可升至80+",
    },
    {
        "id": "earnings_iv_crush_sell_put",
        "name": "财报后 IV Crush 卖 Put",
        "description": "在公司财报公布后立即卖出近期到期的虚值 Put，利用财报后期权 IV 快速收缩（IV crush）获利。通常在24-48小时内平仓。",
        "source": "Option Alpha",
        "instrument": "sell_put",
        "direction": "neutral",
        "style": "income",
        "risk_level": "high",
        "annual_return_range": [30, 60],
        "win_rate_pct": 68,
        "params": {
            "delta_target": 0.2,
            "dte_min": 3,
            "dte_max": 14,
            "profit_target": 0.5,
            "time_stop_days": 2,
        },
        "tags": ["期权", "事件驱动", "IV Crush", "财报"],
        "why_it_works": "财报前市场对不确定性定价使 IV 虚高，财报公布后不确定性消除，IV 快速压缩，期权价格迅速贬值。",
        "best_market": "财报后公司基本面无重大意外，市场反应平稳",
        "worst_market": "财报出现重大利空（盈利大幅低于预期），股价gap down",
    },
    {
        "id": "sector_rotation",
        "name": "板块轮动（Top-Down Sector Rotation）",
        "description": "根据经济周期在不同板块间轮动配置，在领先板块中持有正股或 ETF。利用板块之间的相对强弱差异获取超额收益。",
        "source": "Fidelity Sector Rotation / CFRA",
        "instrument": "stock",
        "direction": "bullish",
        "style": "momentum",
        "risk_level": "low",
        "annual_return_range": [10, 20],
        "win_rate_pct": 55,
        "params": {
            "lookback_days": 90,
            "score_threshold": 70,
            "position_pct": 0.20,
            "max_sector_exposure": 0.40,
        },
        "tags": ["正股", "ETF", "板块", "轮动"],
        "why_it_works": "各板块与经济周期阶段高度相关（消费品先行、科技滞后），系统性轮动可在不同周期阶段持续获益。",
        "best_market": "经济周期转换时期，板块差异化表现明显",
        "worst_market": "系统性市场崩溃，所有板块同步下跌",
    },
    {
        "id": "covered_strangle",
        "name": "持股宽跨卖（Covered Strangle）",
        "description": "持有100股股票同时卖出虚值 Put 和虚值 Call，在 Covered Call 基础上额外收取 Put 权利金。收入最大化，但下行风险翻倍。",
        "source": "tastytrade",
        "instrument": "covered_call",
        "direction": "neutral",
        "style": "income",
        "risk_level": "high",
        "annual_return_range": [20, 35],
        "win_rate_pct": 62,
        "params": {
            "delta_target": 0.2,
            "dte_min": 21,
            "dte_max": 45,
            "profit_target": 0.5,
            "otm_pct": 0.05,
        },
        "tags": ["期权", "卖方", "收入", "高级"],
        "why_it_works": "同时收取两侧权利金，月收益率可达3-5%，适合高 IV 环境和对标的长期看好的投资者。",
        "best_market": "高 IV，横盘震荡，无方向性风险",
        "worst_market": "任何强单边行情（大涨上限被封，大跌双重受损）",
    },
    {
        "id": "protective_put",
        "name": "保险型买 Put（Protective Put）",
        "description": "持有股票同时买入 Put 期权作为对冲保险。损失最大值被锁定（Put行权价以下），上涨潜力无限（减去 Put 费用）。",
        "source": "OCC / CBOE",
        "instrument": "put",
        "direction": "bullish",
        "style": "hedge",
        "risk_level": "low",
        "annual_return_range": [5, 15],
        "win_rate_pct": 50,
        "params": {
            "delta_target": 0.3,
            "dte_min": 60,
            "dte_max": 180,
            "stop_loss_pct": -0.05,
        },
        "tags": ["期权", "买方", "对冲", "保险"],
        "why_it_works": "类似保险原理，支付小额权利金换取对尾部风险的保护，适合持有大额股票仓位的长期投资者。",
        "best_market": "持有核心仓位且担忧短期下行风险，财报前",
        "worst_market": "市场持续上涨，Put 期权时间价值全部损耗",
    },
    {
        "id": "calendar_spread",
        "name": "日历价差（Calendar Spread）",
        "description": "卖出近期到期期权同时买入远期相同行权价期权，利用近期 Theta 衰减快于远期的特性获利。净时间价值为正。",
        "source": "Options Industry Council",
        "instrument": "call",
        "direction": "neutral",
        "style": "income",
        "risk_level": "medium",
        "annual_return_range": [15, 30],
        "win_rate_pct": 55,
        "params": {
            "delta_target": 0.5,
            "dte_min": 7,
            "dte_max": 14,
            "profit_target": 0.25,
        },
        "tags": ["期权", "价差", "时间价值", "高级"],
        "why_it_works": "近期期权 Gamma 高于远期，当标的维持在行权价附近时近期期权贬值速度远快于远期，形成有利的时间价差。",
        "best_market": "低波动横盘，预期价格维持稳定",
        "worst_market": "大幅波动（IV 急剧变化会改变两腿的相对价值）",
    },
    {
        "id": "diagonal_spread",
        "name": "对角价差（Diagonal Spread）",
        "description": "买入远期较低行权价期权（LEAPS），卖出近期较高行权价期权（类似 PMCC）。融合时间价值收益与方向性判断。",
        "source": "Options Play",
        "instrument": "call",
        "direction": "bullish",
        "style": "income",
        "risk_level": "medium",
        "annual_return_range": [20, 40],
        "win_rate_pct": 58,
        "params": {
            "delta_target": 0.7,
            "dte_min": 30,
            "dte_max": 45,
            "otm_pct": 0.05,
        },
        "tags": ["期权", "价差", "LEAPS", "组合"],
        "why_it_works": "以低成本 LEAPS 作为底仓，通过卖出近期期权持续回收成本，最终可能实现零成本持有远期期权。",
        "best_market": "中性偏涨，VIX 适中",
        "worst_market": "标的大幅下跌，或大幅上涨超过近期卖出Call行权价",
    },
    {
        "id": "etf_dip_buy",
        "name": "ETF 定投低吸（Buy the Dip ETF）",
        "description": "在大盘 ETF（SPY/QQQ）下跌超过特定幅度时加仓，利用系统化低吸策略降低持仓成本。结合定期定额和逆势加仓。",
        "source": "Vanguard Research / Dollar Cost Averaging Studies",
        "instrument": "stock",
        "direction": "bullish",
        "style": "mean_reversion",
        "risk_level": "low",
        "annual_return_range": [8, 15],
        "win_rate_pct": 65,
        "params": {
            "dip_threshold": -0.05,
            "position_pct": 0.10,
            "max_positions": 5,
            "stop_loss_pct": -0.20,
        },
        "tags": ["ETF", "定投", "均值回归", "保守"],
        "why_it_works": "长期来看大盘指数持续创新高，在回调中买入降低平均成本，历史数据显示任何10年持有期均盈利。",
        "best_market": "长期牛市中的正常回调",
        "worst_market": "系统性危机（如2000-2002、2008），可能长期套牢",
    },
    {
        "id": "ratio_spread",
        "name": "比例价差（Ratio Spread）",
        "description": "买入1份平值期权，卖出2份虚值期权，构建在轻微上涨/下跌时最优的策略。净成本接近零，但在大幅波动时有无限风险（裸卖端）。",
        "source": "Sheldon Natenberg / Option Volatility and Pricing",
        "instrument": "call",
        "direction": "neutral",
        "style": "income",
        "risk_level": "high",
        "annual_return_range": [15, 35],
        "win_rate_pct": 60,
        "params": {
            "delta_target": 0.5,
            "dte_min": 30,
            "dte_max": 60,
            "profit_target": 0.3,
        },
        "tags": ["期权", "组合", "高级", "比例"],
        "why_it_works": "在中性偏方向市场中可以零成本（甚至净收权利金）建立有最大盈利区间的结构。",
        "best_market": "低 IV 偏中性，标的预期轻微单边运动",
        "worst_market": "大幅突破（裸卖端风险无限），需严格风控",
    },
    {
        "id": "jade_lizard",
        "name": "玉蜥蜴（Jade Lizard）",
        "description": "卖出虚值 Put + 卖出虚值 Bull Call Spread 的组合，总权利金收入大于 Call Spread 价差。上方无风险（Call Spread 对冲），下方为行权价以下的风险。",
        "source": "tastytrade",
        "instrument": "sell_put",
        "direction": "neutral",
        "style": "income",
        "risk_level": "medium",
        "annual_return_range": [20, 35],
        "win_rate_pct": 68,
        "params": {
            "delta_target": 0.25,
            "dte_min": 21,
            "dte_max": 45,
            "profit_target": 0.5,
            "stop_loss_pct": -2.0,
        },
        "tags": ["期权", "卖方", "组合", "高级"],
        "why_it_works": "通过将 Short Strangle 的上方加上保护腿，消除上方无限风险，在保持高权利金收入的同时控制风险。",
        "best_market": "高 IV，轻微看涨偏好，无急剧上涨预期",
        "worst_market": "股价大幅下跌（Put 行权），双边挤压",
    },
    {
        "id": "short_strangle",
        "name": "裸卖宽跨（Short Strangle）",
        "description": "同时卖出虚值 Put 和虚值 Call，在两个行权价之间的区域到期时全额盈利。权利金收入高但两边均有无限风险，需要严格风险管理。",
        "source": "tastytrade",
        "instrument": "sell_put",
        "direction": "neutral",
        "style": "income",
        "risk_level": "high",
        "annual_return_range": [20, 40],
        "win_rate_pct": 68,
        "params": {
            "delta_target": 0.16,
            "dte_min": 30,
            "dte_max": 60,
            "profit_target": 0.5,
            "stop_loss_pct": -2.0,
            "min_iv_rank": 35,
        },
        "tags": ["期权", "卖方", "高收益", "高风险"],
        "why_it_works": "双边收取权利金，历史数据显示 16-delta Strangle 约68-70%概率到期无价值，胜率高于单边。",
        "best_market": "高 IV Rank，预期低波动，宏观事件已过",
        "worst_market": "市场出现单边大幅运动（>2个标准差），损失可能超过权利金10倍",
    },
    {
        "id": "52_week_high_momentum",
        "name": "52周高位动量（52-Week High Momentum）",
        "description": "买入突破52周新高的强势股，利用突破效应继续追涨。基于 George 和 Hwang (2004) 的52周高点效应研究。",
        "source": "George & Hwang 2004 JF / William O'Neil CANSLIM",
        "instrument": "stock",
        "direction": "bullish",
        "style": "momentum",
        "risk_level": "medium",
        "annual_return_range": [15, 28],
        "win_rate_pct": 48,
        "params": {
            "lookback_days": 252,
            "score_threshold": 90,
            "sma_200_above_pct": 0.0,
            "stop_loss_pct": -0.08,
            "position_pct": 0.05,
            "max_positions": 10,
        },
        "tags": ["正股", "动量", "突破", "52周高"],
        "why_it_works": "52周高点在投资者心理上具有显著锚定效应，突破后的动量持续性强，George & Hwang 研究显示超额收益约3.6%/月。",
        "best_market": "牛市，市场风险偏好高，成交量配合",
        "worst_market": "假突破（高位放量后迅速回落），熊市中追高",
    },
]


def get_library() -> list[dict]:
    """返回所有策略，按名称排序"""
    return sorted(STRATEGY_LIBRARY, key=lambda x: x["name"])


def filter_library(
    instrument: str = None,
    direction: str = None,
    style: str = None,
    risk_level: str = None,
    min_return: int = None,
) -> list[dict]:
    """按条件过滤策略库"""
    results = STRATEGY_LIBRARY.copy()

    if instrument and instrument != "all":
        results = [s for s in results if s["instrument"] == instrument]

    if direction and direction != "all":
        results = [s for s in results if s["direction"] == direction]

    if style and style != "all":
        results = [s for s in results if s["style"] == style]

    if risk_level and risk_level != "all":
        results = [s for s in results if s["risk_level"] == risk_level]

    if min_return:
        # Filter: either the lower bound meets it, or the upper bound meets it (strategy CAN reach the target)
        results = [s for s in results if s["annual_return_range"][1] >= min_return]

    return sorted(results, key=lambda x: x["name"])


def get_strategy_by_id(strategy_id: str):
    """根据 id 获取策略"""
    for s in STRATEGY_LIBRARY:
        if s["id"] == strategy_id:
            return s
    return None
